version: '3'
services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: swapi-client
    ports:
      - "3000:3000"
    volumes:
      - ./src:/src
    env_file:
      - ./.env.local
    